spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/ROUTE}
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
  flyway:
    baseline-on-migrate: true

server:
  port: ${PORT:8081}

